// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var retinaImages;
    if (window.devicePixelRatio >= 2) {
      retinaImages = $('img[data-retina]');
      return retinaImages.each(function(i) {
        return retinaImages[i].src = $(retinaImages[i]).data('retina');
      });
    }
  });

}).call(this);
