// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    if (window.devicePixelRatio >= 2) {
      return $('img[data-retina]').each(function() {
        this.src = $(this).data('retina');
        return this;
      });
    }
  });

}).call(this);
